version: "3.8"

services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.15.0
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true   # - security 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.15.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200"]'
      OPENSEARCH_SECURITY_DISABLED: 'true'  
    depends_on:
      - opensearch-node1

  webapp:
    build: ./app
    container_name: opensearch-webapp
    depends_on:
      - opensearch-node1
    ports:
      - "8000:8000"
